---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.zabbix_repository
      zabbix_repository_cleanup_requirements: false
      zabbix_repository_revert_crypto_policy: false
